[package]
name = "ethiopic-numerals"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Convert to Ethiopic Numerals"
repository = "https://github.com/frectonz/ethiopic-numerals"

[dependencies]
